# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.12-slim
WORKDIR /app

# Install build dependencies, install runtime dependencies and install our package
COPY . /app
RUN apt-get update \
    && apt-get install -y --no-install-recommends gcc libffi-dev python3-dev \
    && pip install --upgrade pip \
    && pip install fastmcp httpx pyyaml \
    && pip install . \
    && apt-get purge -y gcc libffi-dev python3-dev \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/*

# Default command
CMD ["openapi-slice-mcp"]
